

services:
  postgres:
    image: postgres:16.3
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpass
      POSTGRES_DB: tickets
    ports:
      - "5432:5432"
    volumes:
      
      - pgdata:/var/lib/postgresql/data

  mongodb:
    image: mongo:7.0
    container_name: mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: adminpass
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  redis:
    image: redis:7.2.5
    container_name: redis
    restart: always
    ports:
      - "6379:6379"

volumes:
  pgdata:
  mongodb_data:
